#name: CI/CD Matrix Deploy
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        environment: [dev, qat, stg, prd]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Deploy ${{ matrix.environment }}
#        run: dotnet run --project metaCICD/metaCICD.csproj ${{ matrix.environment }}

name: CI/CD Matrix Deployment

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy-container:
    name: Prepare Deployment Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add steps to prepare the deployment container

  deploy:
    name: Deploy Services
    runs-on: ubuntu-latest
    needs: [deploy-container]

    strategy:
      max-parallel: 0
      fail-fast: true
      matrix:
        env: [dev,qat,stg,prd]
        include:
          - env: dev
            cluster: dev-cluster
            service: jobposting-processing
            user: admin-DEV
            kafka: kafka/dev/path
            group: job-posting-dev
            k_cluster: chamomile
            opensearch: opensearch/public/dev/masteruser
          - env: qat
            cluster: qat-cluster
            service: jobposting-processing
            user: admin-QAT
            kafka: kafka/qat/path
            group: job-posting-qat
            k_cluster: chamomile
            opensearch: opensearch/public/qat/masteruser
          - env: stg
            cluster: stg-cluster
            service: jobposting-processing
            user: admin-STG
            kafka: kafka/stg/path
            group: job-posting-stg
            k_cluster: hippos
            opensearch: opensearch/public/stg/masteruser
          - env: prd
            cluster: prd-cluster
            service: jobposting-processing
            user: admin-PRD
            kafka: kafka/prd/path
            group: job-posting-prd
            k_cluster: hippos
            opensearch: opensearch/public/prd/masteruser

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Service
        run: |
          echo "Deploying service for environment ${{ matrix.env }}..."
          # Add your deployment script here
