#name: CI/CD Matrix Deploy
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        environment: [dev, qat, stg, prd]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Deploy ${{ matrix.environment }}
#        run: dotnet run --project metaCICD/metaCICD.csproj ${{ matrix.environment }}

name: CI/CD Matrix Deployment

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy Services
    runs-on: self-hosted
    needs: [deploy-container]

    strategy:
      max-parallel: 0
      fail-fast: true
      matrix:
        env: [dev,qat,stg,prd]
        include:
          - env: dev
            cluster: apollo-jupiter-tango
            service: common-ers-jobposting-processing
            user: tango-admin-DEV
            kafka: common-services/atlas-kafka/atlas-pre/lavender
            group: cs-job-posting-dev-lavender
            k_cluster: lavender
            opensearch: atlas/opensearch/ers-public/dev/masteruser
          - env: qat
            cluster: apollo-jupiter-tango
            service: common-ers-jobposting-processing
            user: tango-admin-QAT
            kafka: common-services/atlas-kafka/atlas-pre/lavender
            group: cs-job-posting-qat-lavender
            k_cluster: lavender
            opensearch: atlas/opensearch/ers-public/qat/masteruser
          - env: stg
            cluster: apollo-jupiter-tango
            service: common-ers-jobposting-processing
            user: tango-admin-STG
            kafka: common-services/atlas-kafka/atlas-prd/hippocrates
            group: cs-job-posting-stg-hippocrates
            k_cluster: hippocrates
            opensearch: atlas/opensearch/ers-public/stg/masteruser
          - env: prd
            cluster: apollo-jupiter-tango
            service: common-ers-jobposting-processing
            user: tango-admin-PRD
            kafka: common-services/atlas-kafka/atlas-prd/hippocrates
            group: cs-job-posting-prd-hippocrates
            k_cluster: hippocrates
            opensearch: atlas/opensearch/ers-public/prd/masteruser

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Service
        run: |
          echo "Deploying service for environment ${{ matrix.env }}..."
          # Add your deployment script here
